### ISSUE TITLE
Manual assignment of pairs of files

### ISSUE THREAD

**Issue by koppor** [tsantalis/RefactoringMiner#703]
Context: https://github.com/JabRef/jabref/pull/11180/files

There was code moved from `src/main/java/org/jabref/gui/frame/JabRefFrame.java` to `src/main/java/org/jabref/gui/frame/JabRefFrameViewModel.java`. E.g., `storeLastOpenedFiles` was moved there. I want to see an AST diff there.

Maybe, the use case is that methods go from one file n > 1 other files, which seems to be unsupported currently.

For me, it would be OK, to have a list of candidate files where changes are in and that I select one of the file for viewing (and then getting the MonacoDiff)

---

`src/main/java/org/jabref/gui/frame/JabRefFrame.java`

```diff
-    void storeLastOpenedFiles(List<Path> filenames, Path focusedDatabase) {
-        if (prefs.getWorkspacePreferences().shouldOpenLastEdited()) {
-            // Here we store the names of all current files. If there is no current file, we remove any
-            // previously stored filename.
-            if (filenames.isEmpty()) {
-                prefs.getGuiPreferences().getLastFilesOpened().clear();
-            } else {
-                prefs.getGuiPreferences().setLastFilesOpened(filenames);
-                prefs.getGuiPreferences().setLastFocusedFile(focusedDatabase);
-            }
-        }
-    }
```

`src/main/java/org/jabref/gui/frame/JabRefFrameViewModel.java`

```diff
+    void storeLastOpenedFiles(List<Path> filenames, Path focusedDatabase) {
+        if (prefs.getWorkspacePreferences().shouldOpenLastEdited()) {
+            // Here we store the names of all current files. If there is no current file, we remove any
+            // previously stored filename.
+            if (filenames.isEmpty()) {
+                prefs.getGuiPreferences().getLastFilesOpened().clear();
+            } else {
+                prefs.getGuiPreferences().setLastFilesOpened(filenames);
+                prefs.getGuiPreferences().setLastFocusedFile(focusedDatabase);
+            }
+        }
+    }
```

**Comment by tsantalis** [comment]
@koppor

`storeLastOpenedFiles()` is shown as moved to `JabRefFrameViewModel` in the diff.

![Screenshot from 2024-04-11 16-43-56](https://github.com/tsantalis/RefactoringMiner/assets/1483516/c205e280-430f-4466-bb03-e82577ba3733)

@pouryafard75
Maybe, we could have something like a tooltip/popup that shows the diff when you hover over the moved method.

**Comment by koppor** [comment]
Side comment (not sure if I should open a new issue)

I don't get the semantics of red and green. In the screenshot the red and green text seems to be the same, but one is marked red, the other one green.

![grafik](https://github.com/tsantalis/RefactoringMiner/assets/1366654/99144846-e3b5-4b24-b030-76a7ce7cdbb3)

---

Tracing information: The diff was created by issuing following command

    docker run -p 6789:6789  -v c:\users\koppor\rmc:/diff tsantalis/refactoringminer diff --url https://github.com/JabRef/jabref/pull/11180

**Comment by koppor** [comment]
I think, what would help me is to have some letters/icons between the line numbers and the text. For instance `M` for moved to another file.

**Comment by koppor** [comment]
Side comment: I miss the connecting lines of IntelliJ. It is so hard for me to correlate left and right - even if a click (somehow) relocates the other scroll pane.

![grafik](https://github.com/tsantalis/RefactoringMiner/assets/1366654/0ff1de29-0a73-4cd3-8678-1aee69ff6fc3)

**Comment by koppor** [comment]
Fun fact: IntelliJ does not recognize that diff. Thus, I can only show at other place how IntelliJ displays:

![grafik](https://github.com/tsantalis/RefactoringMiner/assets/1366654/e197f864-9b5f-44d4-a29f-fd2833b64911)

Note the more lighter colors and the better color contrast?

They use gray for deletion (maybe because of colorblind people)?

![grafik](https://github.com/tsantalis/RefactoringMiner/assets/1366654/348223b4-80f1-4137-98b8-f01aedbc69fc)

**Comment by tsantalis** [comment]
@koppor @pouryafard75

Indeed, we need to do a lot to improve the UI look and feel. I agree with all your comments.

To summarize all points in the issue:

- [ ] Improve the highlighting of comments within moved code https://github.com/tsantalis/RefactoringMiner/issues/703#issuecomment-2051108649
- [ ] Avoid multiple move tool-tips. Possibly replace it with a single tool-tip that shows the moved code diff https://github.com/tsantalis/RefactoringMiner/issues/703#issuecomment-2051128301
- [ ] Introduce connecting lines between left and right side https://github.com/tsantalis/RefactoringMiner/issues/703#issuecomment-2051136238
- [ ] Use a different colour pallette more appropriate for colorblind people https://github.com/tsantalis/RefactoringMiner/issues/703#issuecomment-2051155616

**Comment by koppor** [comment]
Additionally, when opening the editor, it should scroll to the first diff. Example: When diffing https://github.com/openjdk/jfx/commit/974bf468c8261c61f8087aa6132824993ae89afd, I need to scroll down.

---

The commit https://github.com/openjdk/jfx/commit/974bf468c8261c61f8087aa6132824993ae89afd is also a motivation for the arrows.

![image](https://github.com/tsantalis/RefactoringMiner/assets/1366654/db0e0d88-0a5c-45ad-bcef-3a21325d558a)

---

Oh, I don't see added code on the right side?

On GitHub, I see the added lines:

![image](https://github.com/tsantalis/RefactoringMiner/assets/1366654/bc70aedf-a251-4ffd-8856-e59978a175b2)

OK, all are green... I would like to have a "mix" of current RefactoringMiner and the GitHub diff...

**Comment by tsantalis** [comment]
@koppor 

This is an interesting case in terms of diff accuracy.
On the left side, there are 11 arguments, while on the right side there are 13 arguments.

This possibly means that 2 arguments are newly added, but it's a bit hard to understand what is the correct diff.

L81 seems it moved to R93. Is this correct?

L89 is now R95. Is this correct?

What are the truly newly added arguments?
It seems some arguments were reordered, some added, some updated with different numbers.

**Comment by koppor** [comment]
> This is an interesting case in terms of diff accuracy.

:-)

Therefore I was asking about arrows to check if the tool would match some intuition.

> This possibly means that 2 arguments are newly added, but it's a bit hard to understand what is the correct diff.

Sure :) - I also forgot, what I added :)

> L81 seems it moved to R93. Is this correct?

Yes.

> L89 is now R95. Is this correct?

Yes. Fixed-test-case.

> What are the truly newly added arguments? It seems some arguments were reordered, 

No reordering of arguments. It should be updates only to fix the expected value at the beginning (first parameter). 

- right L82 fixes left L83
- right L83 fixes left L84
- right L86 fixes left L85 (consistency to right L85)
- left L88 got lost somehow? (or could be now right L87)
- right L95 fixes left L89

**Comment by tsantalis** [comment]
@koppor 

I have great news. We implemented additional diffs for moved code.
This means that for a given file, there could be multiple diffs, if some methods or attributes have been moved to another class, or extracted to a new class.

For PR https://github.com/JabRef/jabref/pull/11180/files
The new diff is
`JabRefFrame.java` → `JabRefFrameViewModel.java`

**Comment by tsantalis** [comment]
@koppor 
I fixed the mapping of comments in PR https://github.com/JabRef/jabref/pull/11180
See issue https://github.com/tsantalis/RefactoringMiner/issues/703#issuecomment-2051108649

![Screenshot from 2024-10-06 19-18-38](https://github.com/user-attachments/assets/2dd0c4a5-3ee0-4304-9121-310a2fd62bc5)

**Comment by tsantalis** [comment]
@koppor 
Happy New Year Oliver! Thank you for your valuable feedback.
I wish you all the best for 2025.

**Comment by koppor** [comment]
I would really like to raise my wish again. Example from: https://github.com/tsantalis/RefactoringMiner/issues/894

![Image](https://github.com/user-attachments/assets/d306db18-658a-46ff-8f4d-11cc76a80c2f)

I would like to see the diff between the two yellow-marked files - to see how they relate. That request could even trigger some backend functionality, re-evaluating a diff.
